In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("train (6).csv")

df.head(10)

,patient_id,age,gender,bmi,heart_rate,systolic_bp,diastolic_bp,respiratory_rate,oxygen_saturation,glucose,creatinine,wbc_count,severity_score,ventilation_required,chronic_conditions,survived_icu
0,ICU_00301,51,1,20.0,78.6,128.3,67.1,13.7,92.4,40.0,2.98,1.45,14,0,1,1
1,ICU_05027,54,0,25.5,124.2,146.4,91.9,19.4,83.9,129.6,0.31,4.67,14,1,1,0
2,ICU_00475,57,0,27.6,124.7,127.6,78.3,10.4,100.0,274.0,4.37,10.32,24,1,1,0
3,ICU_04732,43,1,24.8,89.9,123.3,67.3,17.8,92.5,218.4,1.94,24.55,15,1,4,0
4,ICU_01889,61,0,21.4,96.1,187.0,71.6,25.1,86.2,126.5,0.37,8.47,3,0,1,1
5,ICU_02045,82,0,23.5,89.4,122.8,64.7,34.2,100.0,220.5,1.83,1.00,6,0,3,0
6,ICU_04097,51,1,NaN,57.1,143.2,53.8,NaN,NaN,90.2,NaN,NaN,3,0,0,0
7,ICU_05817,65,1,28.6,54.1,114.3,61.0,20.8,97.9,221.8,0.49,7.63,19,0,5,1
8,ICU_00734,80,0,24.1,62.6,123.0,76.4,15.6,100.0,135.4,0.42,6.69,3,1,1,0
9,ICU_03391,47,1,12.1,77.5,158.0,69.0,27.8,100.0,185.9,0.30,13.70,20,0,1,1

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,4580.0,61.436245,17.154096,18.0,50.000,62.00,73.0000,95.000000
gender,4580.0,0.532096,0.499023,0.0,0.000,1.00,1.0000,1.000000
bmi,3959.0,27.009093,7.507568,9.0,21.600,26.40,31.7000,57.000000
heart_rate,4580.0,99.210786,84.479186,30.0,73.900,89.00,103.7000,1207.839980
systolic_bp,4580.0,133.573375,117.907364,60.0,98.600,118.30,138.8000,1645.595945
diastolic_bp,4580.0,71.957969,17.337162,30.0,59.800,72.20,83.8000,130.000000
respiratory_rate,4005.0,18.061673,5.886609,6.0,13.900,18.00,22.1000,37.300000
oxygen_saturation,3977.0,94.565954,4.385576,78.4,91.700,95.00,98.4000,100.000000
glucose,4580.0,159.452983,156.701082,40.0,99.775,141.10,183.8250,2256.210085
creatinine,3939.0,1.373065,1.828402,0.3,0.360,0.89,1.7500,48.737770
wbc_count,3772.0,10.136159,9.748162,1.0,2.840,7.00,14.2825,50.000000
severity_score,4580.0,12.020961,7.175003,0.0,6.000,12.00,18.0000,24.000000
ventilation_required,4580.0,0.447162,0.497255,0.0,0.000,0.00,1.0000,1.000000
chronic_conditions,4580.0,1.623144,1.402704,0.0,0.000,1.00,2.0000,5.000000
survived_icu,4580.0,0.643668,0.478967,0.0,0.000,1.00,1.0000,1.000000